version: "3.8"
services:
  apache:
    image: httpd:${APACHE_VERSION:-bullseye}
    build:
      context: './apache/'
      args:
        PROJECT_ROOT: ${PROJECT_ROOT:-/var/www/html}
    env_file:
      - ./apache/.env
    environment:
      - APACHE_CONF_DIR=${APACHE_CONF_DIR:-/usr/local/apache2}
    # Use host networking
    networks:
      web: {}
    container_name: apache
    ports:
      - target: 80
        host_ip: 0.0.0.0
        published: 8080
        mode: host
    volumes:
      - type: bind
        source: www
        target: ${WEB_ROOT_CONTAINER:-/var/www/html}
        read_only: false
      - type: bind
        source: ./apache/conf
        target: ${APACHE_CONF_DIR}/conf-enabled
      - type: bind
        source: ./apache/sites
        target: ${APACHE_CONF_DIR}/sites-enabled
  base_img:
    image: ubuntu:22.04
    container_name: base_img
    build:
      context: './base-img/'
    networks:
      web: {}
    volumes:
      - type: volume
        source: img_workspace
        target: /workspace
        volume:
          nocopy: false
    privileged: true
    user: root
    working_dir: /workspace
    restart: "no"
  ext_img:
    image: ubuntu:22.04
    container_name: ext_img
    build:
      context: './ext-img/'
    networks:
      web: {}
    volumes:
        - type: volume
          source: img_workspace
          target: /workspace
    depends_on:
      base_img:
        condition: service_started
    privileged: true
    user: root
    working_dir: /workspace
    tty: true
    stdin_open: true
    restart: "no"
# Volumes
volumes:
  # The volume for the web root.
  www:
    driver: local
    driver_opts:
      type: bind
      device: ./www/
  img_workspace:
    name: img_workspace
    labels:
      img_workspace: img_workspace
    driver: local
# Networks
networks:
  # The network for the web server (Apache)
  web:
    ipam:
      driver: default
      config:
        - subnet: 10.64.0.0/12
          ip_range: 10.68.0.0/24
          gateway: 10.64.0.1

  internet-access:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.64.0/24
          ip_range: 192.168.64.0/24
          gateway: 192.168.64.1